title: Manuel I. Jimenez
logo: img/foto_MJ.png
description: Postdoctoral Researcher <br> Dept. of Agricultural Economics <br> Purdue University <div id="badges"> :email: <br> <a href="https://www.linkedin.com/in/manuel-i-jimenez-ph-d-a60835103/"> <img src="https://img.shields.io/badge/LinkedIn-blue?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn Badge"/></a> </div>
#show_downloads:
theme: jekyll-theme-minimal
