title: Manuel I. Jimenez
#logo:/C:/User/manji/OneDrive/Desktop/foto_MJ.png
description: Postdoctoral Researcher
description: Dept. of Agricultural Economics
description: Purdue University
#show_downloads:
theme: jekyll-theme-minimal
