title: Manuel I. Jimenez
#logo:/C:/User/manji/OneDrive/Desktop/foto_MJ.png
description: Postdoctoral Researcher <br> Dept. of Agricultural Economics
#Purdue University
#show_downloads:
theme: jekyll-theme-minimal
